## Utiliza extensioin REST Client para ejecutar estas peticiones
## 
## Este archivo contiene las peticiones para probar el servicio de encuestas


## Peticion de encuesta, retorna la lista de preguntas para la encuesta
GET http://localhost:1234/usr/encuesta


## La fecha, hora y id de banio y tipo de incidente son determinados en el backend
## Envio de respuesta de una encuesta VALIDA
POST http://localhost:1234/usr/encuesta
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
    "edificio": "100",
    "seccion": "segundo piso",
    "genero": "hombre",
    "descripcion": "Lavabo tapado con papel"
}
------MyBoundary
Content-Disposition: form-data; name="foto"; filename="imagen.png"
Content-Type: image/png

< ./vandalizmo.jpg
------MyBoundary--


## Envio de respuesta de una encuesta INVALIDA por datos incorrectos 
## (no existe el edificio 1124321245))
POST http://localhost:1234/usr/encuesta
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
    "edificio": "1124321245",
    "planta": "alta",
    "genero": "mujer",
    "descripcion": "Lababo tapado con papel",
}
------MyBoundary
Content-Disposition: form-data; name="foto"; filename="imagen.png"
Content-Type: image/png

< ./vandalizmo.jpg
------MyBoundary--


## Envio de respuesta de una encuesta INVALIDA por falta de datos 
## (no indica si es de hombre o mujer))
POST http://localhost:1234/usr/encuesta
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json
{
    "banio": "600",
    "seccion": "primer piso",
    "descripcion": "Lababo tapado con papel",
}
------MyBoundary
Content-Disposition: form-data; name="foto"; filename="imagen.png"
Content-Type: image/png

< ./vandalizmo.jpg
------MyBoundary--

