### En este archivo se recupera los incidentes de la base de datos
## se diferencia de encuestas por que estos son para recuperar la informacion de la baase de datos


### Peticionar todos los incidentes sin fotos
GET http://localhost:1234/incidentes


### Peticionar todos los incidentes de cierto edificio sin fotos
GET http://localhost:1234/incidentes/?edificio=100

### Peticionar todos los incidentes de el edificio 100 y de banio de hombres en la planta alta
GET http://localhost:1234/incidentes/?edificio=100&banio=hombre&planta=alta

### Peticionar entre dos fechas
GET http://localhost:1234/incidentes/?fechaAntesDe=2023-10-01&fechaDespuesDe=2023-10-31

### Peticionar entre fecha y un lugar especifico
GET http://localhost:1234/incidentes/?fechaAntesDe=2023-10-01&fechaDespuesDe=2023-10-31&edificio=100&banio=hombre&planta=alta

### Peticionar cierta foto de incidente segun id 
GET http://localhost:1234/incidentes/foto/1/


