### En este archivo se recupera los incidentes de la base de datos
## se diferencia de encuestas por que estos son para recuperar la informacion de la base de datos


### Peticionar todos los incidentes sin fotos
GET http://localhost:1234/incidentes


### Peticionar todos los incidentes de cierto edificio sin fotos
GET http://localhost:1234/incidentes/?fechaDespuesDe=2025-07T17:29:09

### Peticionar todos los incidentes de el edificio 100 y de banio de hombres en la planta alta
    GET http://localhost:1234/incidentes/?edificio=100&banio=hombre&planta=alta

### Peticionar cierta foto de incidente segun id 
GET http://localhost:1234/incidentes/foto/1/


### Agregar un incidente
## Otros campos seran agregados dentro del lado del servidor
POST http://localhost:1234/incidentes
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="data"
#Content-Type: application/json

# Con estos campos se crea el reporte de incidente
{
    "ubicacion": "100 planta alta",
    "tipo_incidente": "Falta de jabón",
    "genero_bano": "hombre",
    "descripcion": "Falta jabón en ambos dispensadores"
    
}
------MyBoundary
Content-Disposition: form-data; name="foto"; filename="imagen.png"
Content-Type: image/png

< ./vandalizmo.jpg
------MyBoundary--

### Agregar un incidente sin foto
POST http://localhost:1234/incidentes
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="data"

{
    "ubicacion": "100 planta alta",
    "tipo_incidente": "Falta de jabón",
    "genero_bano": "hombre",
    "descripcion": "Falta jabón en ambos dispensadores"
    
}
------MyBoundary--
