### Agregar Tipo  de Incidente

POST http://localhost:1234/tipos_incidentes/agregar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJub21icmUiOiJhZG1pbiIsImlhdCI6MTc0ODkzMDU1NywiZXhwIjoxNzQ4OTM3NzU3fQ.Z9pISfHsA61oanJJGt8FAfrcuolC2T5Y-mpJiCkhmek
Content-Type: application/json

{
    "nombre": "Popo en el piso"
}