### En este archivo se muestra las apis que utilizaria un usuario
## estas son para referencia y puede que requieran utilizar tokens de sesion


### Iniciar sesion del usuario
## Inicio de sesion del usuario base
## Retorna token de sesion

##USUARIO ADMIN: admin
## CONTRASEÑA ADMIN: admin123
POST http://localhost:1234/usuario/login
Content-Type: application/json

{
  "nombre": "admin",
  "contrasena_hash": "admin123"
}

### Crear un usuario
## Requiere iniciar sesion como un usuario, por lo que ocupan tokens
POST http://localhost:1234/usuario/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJub21icmUiOiJhZG1pbiIsImlhdCI6MTc0NzgxNTUxNSwiZXhwIjoxNzQ3ODIyNzE1fQ.yP8mcyVzrWvza8DxqGF4doB7AI57QQJ4yiniZCrvixs
Content-Type: application/json

{
  "nombre": "alexia",
  "email": "alexia@ejemplo.com",
  "telefono": "6461234567",
  "contrasena_hash": "123"
}

### Borrar usuario propio
## Ocupa iniciar sesion como dicho usuario y de este token obtiene que usuario es
DELETE http://localhost:1234/usuario
