### En este archivo se muestra las apis que utilizaria un usuario
## estas son para referencia y puede que requieran utilizar tokens de sesion


### Iniciar sesion del usuario
## Inicio de sesion del usuario base
## Retorna token de sesion

##USUARIO ADMIN: admin
## CONTRASEÑA ADMIN: admin123
POST http://localhost:1234/usuario/login
Content-Type: application/json

{
  "nombre": "admin",
  "contrasena_hash": "admin123"
}

###

## Actualizar perfil del usuario
PATCH http://localhost:1234/usuario/actualizar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJub21icmUiOiJhZG1pbiIsImlhdCI6MTc0ODQxMzM0NCwiZXhwIjoxNzQ4NDIwNTQ0fQ.U5X4pO5BfCfAKQffr33Y4jDtU7ejgX37s8ce-J10ukk
Content-Type: application/json

{
  "nombre": "admin",
  "contrasena_hash": "admin123"
}

### Crear un usuario
## Requiere iniciar sesion como un usuario, por lo que ocupan tokens
GET http://localhost:1234/usuario/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c3VhcmlvIjoxLCJub21icmUiOiJhZG1pbiIsImlhdCI6MTc0ODQxNTMxMiwiZXhwIjoxNzQ4NDIyNTEyfQ._G_zNQeZTwNOvUOcph4xbWlRX_8_G4x-xlWAjDJm5UA
Content-Type: application/json

###

GET http://localhost:1234/usuario/perfil
Authorization: : Bearer 



### Actualizar perfil del usuario

### Borrar usuario propio
## Ocupa iniciar sesion como dicho usuario y de este token obtiene que usuario es
DELETE http://localhost:1234/usuario
